#ifndef __INTERFACE_TYPES__
#define __INTERFACE_TYPES__

enum IntfL2Mode
{
    LAN_MODE_NONE,
    LAN_ACCESS_MODE,
    LAN_TRUNK_MODE
};

enum InterfaceType_t {

    INTF_TYPE_PHY,
    INTF_TYPE_VLAN,
    INTF_TYPE_GRE_TUNNEL,
    INTF_TYPE_LOOPBACK,
    INTF_TYPE_UNKNOWN
};


/* Interface common Configuration Bits */
#define INTF_CONFIG_SUPPORT_ALL 0
#define INTF_CONFIG_NOT_SUPPORTED_IP_ADDRESS 1
#define INTF_CONFIG_NOT_SUPPORTED_METRIC 2
#define INTF_CONFIG_NOT_SUPPORTED_TSP 4
#define INTF_CONFIG_NOT_SUPPORTED_SWITCHPORT 8
#define INTF_CONFIG_NOT_SUPPORTED_VLAN 16
#define INTF_CONFIG_NOT_SUPPORTED_UP_DOWN   32
#define INTF_CONFIG_NOT_SUPPORTED_VLAN 64
#define INTF_CONFIG_NOT_SUPPORTED_TRACEOPTIONS 128


#endif 